export const GET_AUTH_TOKEN_REQUEST = "GET_AUTH_TOKEN_REQUEST";
export const GET_AUTH_TOKEN_SUCCESS = "GET_AUTH_TOKEN_SUCCESS";
export const GET_AUTH_TOKEN_FAILED = "GET_AUTH_TOKEN_FAILED";

export const CLEAN_AUTH_TOKEN_REQUEST = "CLEAN_AUTH_TOKEN_REQUEST";
export const CLEAN_AUTH_TOKEN_SUCCESS = "CLEAN_AUTH_TOKEN_SUCCESS";

export const REGISTER_USER_WITH_PLAN_AND_COMPANY_REQUEST =
  "REGISTER_USER_WITH_PLAN_AND_COMPANY_REQUEST";
export const REGISTER_USER_WITH_PLAN_AND_COMPANY_SUCCESS =
  "REGISTER_USER_WITH_PLAN_AND_COMPANY_SUCCESS";
export const REGISTER_USER_WITH_PLAN_AND_COMPANY_FAILED =
  "REGISTER_USER_WITH_PLAN_AND_COMPANY_FAILED";

export const ADD_PLAN_TO_USER_REQUEST = "ADD_PLAN_TO_USER_REQUEST";
export const ADD_PLAN_TO_USER_SUCCESS = "ADD_PLAN_TO_USER_SUCCESS";
export const ADD_PLAN_TO_USER_FAILED = "ADD_PLAN_TO_USER_FAILED";

export const ADD_COMPANY_TO_USER_REQUEST = "ADD_COMPANY_TO_USER_REQUEST";
export const ADD_COMPANY_TO_USER_SUCCESS = "ADD_COMPANY_TO_USER_SUCCESS";
export const ADD_COMPANY_TO_USER_FAILED = "ADD_COMPANY_TO_USER_FAILED";

export const GET_USER_DEATILS_REQUEST = "GET_USER_DEATILS_REQUEST";
export const GET_USER_DEATILS_SUCCESS = "GET_USER_DEATILS_SUCCESS";
export const GET_USER_DEATILS_FAILED = "GET_USER_DEATILS_FAILED";

export const GET_USER_PREFERENCE_REQUEST = "GET_USER_PREFERENCE_REQUEST";
export const GET_USER_PREFERENCE_SUCCESS = "GET_USER_PREFERENCE_SUCCESS";
export const GET_USER_PREFERENCE_FAILED = "GET_USER_PREFERENCE_FAILED";

export const UPDATE_USER_DEATILS_REQUEST = "UPDATE_USER_DEATILS_REQUEST";
export const UPDATE_USER_DEATILS_SUCCESS = "UPDATE_USER_DEATILS_SUCCESS";
export const UPDATE_USER_DEATILS_FAILED = "UPDATE_USER_DEATILS_FAILED";

export const UPDATE_USER_PREFERENCE_REQUEST = "UPDATE_USER_PREFERENCE_REQUEST";
export const UPDATE_USER_PREFERENCE_SUCCESS = "UPDATE_USER_PREFERENCE_SUCCESS";
export const UPDATE_USER_PREFERENCE_FAILED = "UPDATE_USER_PREFERENCE_FAILED";

export const GET_GROUP_LIST_REQUEST = "GET_GROUP_LIST_REQUEST";
export const GET_GROUP_LIST_SUCCESS = "GET_GROUP_LIST_SUCCESS";
export const GET_GROUP_LIST_FAILED = "GET_GROUP_LIST_FAILED";
