export const GET_COMPANY_LIST_REQUEST = "GET_COMPANY_LIST_REQUEST";
export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS";
export const GET_COMPANY_LIST_FAILED = "GET_COMPANY_LIST_FAILED";

export const CHANGE_COMPANY = "CHANGE_COMPANY";

export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAILED = "GET_COMPANY_FAILED";

export const SET_COMPANY_REQUEST = "SET_COMPANY_REQUEST";
export const SET_COMPANY_SUCCESS = "SET_COMPANY_SUCCESS";
export const SET_COMPANY_FAILED = "SET_COMPANY_FAILED";

export const GET_COMPANY_TYPE_LIST_REQUEST = "GET_COMPANY_TYPE_LIST_REQUEST";
export const GET_COMPANY_TYPE_LIST_SUCCESS = "GET_COMPANY_TYPE_LIST_SUCCESS";
export const GET_COMPANY_TYPE_LIST_FAILED = "GET_COMPANY_TYPE_LIST_FAILED";

export const ADD_COMPANY_REQUEST = "ADD_COMPANY_REQUEST";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAILED = "ADD_COMPANY_FAILED";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAILED = "UPDATE_COMPANY_FAILED";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAILED = "DELETE_COMPANY_FAILED";
