export const GET_CSIB_LATEST_CUSTOMERS_REQUEST =
  "GET_CSIB_LATEST_CUSTOMERS_REQUEST";
export const GET_CSIB_LATEST_CUSTOMERS_SUCCESS =
  "GET_CSIB_LATEST_CUSTOMERS_SUCCESS";
export const GET_CSIB_LATEST_CUSTOMERS_FAILED =
  "GET_CSIB_LATEST_CUSTOMERS_FAILED";
export const GET_CSIB_LATEST_SUPPLIERS_REQUEST =
  "GET_CSIB_LATEST_SUPPLIERS_REQUEST";
export const GET_CSIB_LATEST_SUPPLIERS_SUCCESS =
  "GET_CSIB_LATEST_SUPPLIERS_SUCCESS";
export const GET_CSIB_LATEST_SUPPLIERS_FAILED =
  "GET_CSIB_LATEST_SUPPLIERS_FAILED";
export const GET_CSIB_LATEST_INVESTORS_REQUEST =
  "GET_CSIB_LATEST_INVESTORS_REQUEST";
export const GET_CSIB_LATEST_INVESTORS_SUCCESS =
  "GET_CSIB_LATEST_INVESTORS_SUCCESS";
export const GET_CSIB_LATEST_INVESTORS_FAILED =
  "GET_CSIB_LATEST_INVESTORS_FAILED";
export const GET_CSIB_LATEST_BORROWERS_REQUEST =
  "GET_CSIB_LATEST_BORROWERS_REQUEST";
export const GET_CSIB_LATEST_BORROWERS_SUCCESS =
  "GET_CSIB_LATEST_BORROWERS_SUCCESS";
export const GET_CSIB_LATEST_BORROWERS_FAILED =
  "GET_CSIB_LATEST_BORROWERS_FAILED";

export const GET_CSIB_TYPE_LIST_REQUEST = "GET_CSIB_TYPE_LIST_REQUEST";
export const GET_CSIB_TYPE_LIST_SUCCESS = "GET_CSIB_TYPE_LIST_SUCCESS";
export const GET_CSIB_TYPE_LIST_FAILED = "GET_CSIB_TYPE_LIST_FAILED";

export const GET_CSIB_LIST_REQUEST = "GET_CSIB_LIST_REQUEST";
export const GET_CSIB_LIST_SUCCESS = "GET_CSIB_LIST_SUCCESS";
export const GET_CSIB_LIST_FAILED = "GET_CSIB_LIST_FAILED";

export const ADD_CSIB_REQUEST = "ADD_CSIB_REQUEST";
export const ADD_CSIB_SUCCESS = "ADD_CSIB_SUCCESS";
export const ADD_CSIB_FAILED = "ADD_CSIB_FAILED";

export const DELETE_CSIB_REQUEST = "DELETE_CSIB_REQUEST";
export const DELETE_CSIB_SUCCESS = "DELETE_CSIB_SUCCESS";
export const DELETE_CSIB_FAILED = "DELETE_CSIB_FAILED";

export const UPDATE_CSIB_REQUEST = "UPDATE_CSIB_REQUEST";
export const UPDATE_CSIB_SUCCESS = "UPDATE_CSIB_SUCCESS";
export const UPDATE_CSIB_FAILED = "UPDATE_CSIB_FAILED";
