export const GET_EDITOR_LIST_REQUEST = "GET_EDITOR_LIST_REQUEST";
export const GET_EDITOR_LIST_SUCCESS = "GET_EDITOR_LIST_SUCCESS";
export const GET_EDITOR_LIST_FAILED = "GET_EDITOR_LIST_FAILED";

export const ADD_EDITOR_REQUEST = "ADD_EDITOR_REQUEST";
export const ADD_EDITOR_SUCCESS = "ADD_EDITOR_SUCCESS";
export const ADD_EDITOR_FAILED = "ADD_EDITOR_FAILED";

export const UPDATE_EDITOR_REQUEST = "UPDATE_EDITOR_REQUEST";
export const UPDATE_EDITOR_SUCCESS = "UPDATE_EDITOR_SUCCESS";
export const UPDATE_EDITOR_FAILED = "UPDATE_EDITOR_FAILED";

export const DELETE_EDITOR_REQUEST = "DELETE_EDITOR_REQUEST";
export const DELETE_EDITOR_SUCCESS = "DELETE_EDITOR_SUCCESS";
export const DELETE_EDITOR_FAILED = "DELETE_EDITOR_FAILED";
