export const GET_SUPPLIER_LIST_REQUEST = "GET_SUPPLIER_LIST_REQUEST";
export const GET_SUPPLIER_LIST_SUCCESS = "GET_SUPPLIER_LIST_SUCCESS";
export const GET_SUPPLIER_LIST_FAILED = "GET_SUPPLIER_LIST_FAILED";

export const ADD_SUPPLIER_REQUEST = "ADD_SUPPLIER_REQUEST";
export const ADD_SUPPLIER_SUCCESS = "ADD_SUPPLIER_SUCCESS";
export const ADD_SUPPLIER_FAILED = "ADD_SUPPLIER_FAILED";
