export const GET_TRANSACTION_LIST_REQUEST = "GET_TRANSACTION_LIST_REQUEST";
export const GET_TRANSACTION_LIST_SUCCESS = "GET_TRANSACTION_LIST_SUCCESS";
export const GET_TRANSACTION_LIST_FAILED = "GET_TRANSACTION_LIST_FAILED";

export const ADD_TRANSACTION_REQUEST = "ADD_TRANSACTION_REQUEST";
export const ADD_TRANSACTION_SUCCESS = "ADD_TRANSACTION_SUCCESS";
export const ADD_TRANSACTION_FAILED = "ADD_TRANSACTION_FAILED";

export const UPDATE_TRANSACTION_REQUEST = "UPDATE_TRANSACTION_REQUEST";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAILED = "UPDATE_TRANSACTION_FAILED";

export const DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILED = "DELETE_TRANSACTION_FAILED";

export const GET_TOP_TRANSACTION_REQUEST = "GET_TOP_TRANSACTION_REQUEST";
export const GET_TOP_TRANSACTION_SUCCESS = "GET_TOP_TRANSACTION_SUCCESS";
export const GET_TOP_TRANSACTION_FAILED = "GET_TOP_TRANSACTION_FAILED";

export const GET_TRANSACTION_TYPE_REQUEST = "GET_TRANSACTION_TYPE_REQUEST";
export const GET_TRANSACTION_TYPE_SUCCESS = "GET_TRANSACTION_TYPE_SUCCESS";
export const GET_TRANSACTION_TYPE_FAILED = "GET_TRANSACTION_TYPE_FAILED";
